package:
  name: sphinx
  version: !!str 1.3.1

source:
  git_url: https://github.com/sphinx-doc/sphinx
  git_tag: 1.3.1
#  patches:
   # List any patch files here
   # - fix.patch

build:
  preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - sphinx = sphinx:main
    #
    # Would create an entry point called sphinx that calls sphinx.main()
    - sphinx-build = sphinx:main
    - sphinx-quickstart = sphinx.quickstart:main
    - sphinx-apidoc = sphinx.apidoc:main
    - sphinx-autogen = sphinx.ext.autosummary.generate:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - six
    - jinja2
    - pygments
    - docutils
    - snowballstemmer
    - babel
    - alabaster
    - sphinx_rtd_theme

  run:
    - python
    - six
    - jinja2
    - pygments
    - docutils
    - snowballstemmer
    - babel
    - alabaster
    - sphinx_rtd_theme

test:
  # Python imports
  #imports:
  #  - sphinx

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    #- sphinx-build --help,
    #- sphinx-quickstart --help,
    #- sphinx-apidoc --help,
    #- sphinx-autogen --help,

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.  For example
    - nose
    - mock
    #- simplejson

about:
  home: https://github.com/sphinx-doc/sphinx
  license: BSD
  summary: 'Python documentation generator'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
